pipeline{
    agent any
    parameters{
        choice(choices:["withTest", "withoutTest"], description: "Use tests?", name: executeTest)
    }
    stages{
        stage("Clear directory"){
            steps{
                deleteDir()
            }
        }
        stage("Clone repository"){
            steps{
                sh "git clone https://github.com/czechp/jenkins-spring-test.git"
            }
        }
        stage("Build project"){
            steps{
                dir("jenkins-spring-test"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
        when{expression{params.executeTest=="withTest"}}
            steps{
                dir("jenkins-spring-test"){
                    sh "mvn test"
                }
            }
        }
    }
}